apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gboie/argocd-node-app-config.git
    targetRevision: HEAD
    path: node-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: node-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true